/* tslint:disable */
/* eslint-disable */
/**
 * Astarte App Engine API
 * Astarte\'s AppEngine API is the main entry point for any operations which have an impact on devices and their data. Most Astarte applications would want to use this API to interact with devices, stream and receive data, and oversee their fleet.
 *
 * The version of the OpenAPI document: 0.10.2
 * Contact: info@ispirata.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

